# Generated by Django 6.1.1 on 2026-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_studydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydocument',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_model_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='analysis_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
