# Generated by Django 6.1.1 on 2026-09-11 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tutoring', '0004_document_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerConceptState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept_key', models.CharField(max_length=255)),
                ('concept_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'new'), ('developing', 'developing'), ('proficient', 'proficient'), ('needs_reinforcement', 'needs_reinforcement')], default='new', max_length=30)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('likely_gaps', models.JSONField(blank=True, default=list)),
                ('recommended_next_action', models.TextField(blank=True)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_states', to='accounts.appuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'concept_key'), name='unique_user_concept_state')],
            },
        ),
    ]
