# Generated by Django 6.1.1 on 2026-09-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tutoring', '0005_learnerconceptstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('objective', 'objective'), ('theory', 'theory')], max_length=10)),
                ('grading_payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('issued', 'issued'), ('processing', 'processing'), ('consumed', 'consumed')], default='issued', max_length=10)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_tokens', to='accounts.appuser')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'status'], name='tutoring_ev_user_id_2190f6_idx'),
                    models.Index(fields=['expires_at'], name='tutoring_ev_expires_c6a151_idx'),
                ],
            },
        ),
    ]
